### ISSUE TITLE
Error while testing the lambda function after uploading the zip file

### ISSUE THREAD

**Issue by ajeet2511** [TylerPachal/lambda-node-phantom#1]
Hi

I am getting the following error while running your sample code. I have cloned the repo, then created a zip of that using 7z and then uploaded the zip to lambda.

{
  "errorMessage": "Cannot find module '/var/task/index'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:417:25)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)"
  ]
}

Can you please help.

**Comment by mkamla** [comment]
@ajeet2511 make sure you're only zipping/compressing the necessary **files** of the working directory instead of the containing directory itself. Also, be sure to run `npm install` and include the `node_modules` directory in your selection of compressed files.
